version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'theonepichael'
    assignees:
      - 'theonepichael'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'
    groups:
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
      testing:
        patterns:
          - 'vitest'
          - '*test*'
      development:
        dependency-type: 'development'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
